# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='dock',
        ),
        migrations.DeleteModel(
            name='Dock',
        ),
    ]
